name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please include enough detail to reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise bug summary
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Exact steps and inputs
      placeholder: |
        1. Start stack with ...
        2. Open ...
        3. Call ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      description: Paste relevant logs or screenshots
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Docker version, model, commit SHA
